



var i8n={

cancel:"Cancel",
dec:"Dec",
temporarilyClosed:"<br/>(Temporarily Closed)",
tue:"Tue",
creditsOverMaximum:"credits <br/>which is over the maximum of",
unknownSeatAvailability:"<span>Unknown Seat Availability</span>",
pinnedDownClass:"You pinned-down a class that is ",
calssIsOnline:"Class is Online",
theCourse:"The course",
jan:"Jan",
noMoreHonors:"There are no schedules that contain only honors classes. Uncheck 'Show Only Honors Schedules'",
doesNotOccurFilters:"The class you are enrolled in does not occur within the selected filters.",
tipUseArrows:"Use the <strong>arrow keys</strong> to quickly browse your generated schedule results.",
campusesLC:" campuses",
classesSelfConflict:"classes self-conflict",
doesNotoccurLocations:"The selected class does not occur within the selected locations.",
ext:"_en",
sendToWorksheet:"Send CRNs to my Worksheet",
apr:"Apr",
sendToShoppingCart:"Send Schedule to Shopping Cart",
requestedClassNotOffered:"The requested class is not offered at the selected location(s). Include more locations to select the exact class.",
tipShareSave:"<strong>Share or save</strong> your search by copy-pasting your browser's unique URL.",
buildingAndRoomNo:"Building and Room Number",
dropCrns:"You would need to drop the following CRNs to get this schedule: ",
noApplicableClasses:"(No applicable classes)",
unpinningThisCourse:"Unpinning this course would result in too many schedule possibilities. You must reduce the number of enabled classes or pin down different class(es) before unpinning this course.",
enroll:"Enroll",
tipUncheckOnlineOnCampusClasses:"If you hide both online and on-campus classes then you will always have no results. Uncheck 'Online Classes' or 'On-campus classes'.",
jun2:"June",
onlineClassesOnlyCheck:"All courses have 'Online Classes Only' or 'Learn on Demand Only' selected, therefore this checkbox does not apply.",
clickToUnpin:"Click to unpin course",
apr2:"April",
tipClickToPin:"<strong>Click on classes</strong> to pin them down temporarily. This will narrow the number of results.",
tipCreateShareLink:"<strong>Share</strong> this schedule by clicking 'Create Share Link'.",
overlappingTimes:" held at overlapping times during the week.",
increaseAccessibility:"Increase Accessibility",
addTimeToAvoid:"Add Personal Times",
campusChange:"Warning: Campus change - ensure adequate travel time.",
sun:"Sun",
tryAllClasses:"Try all classes",
warningNotAllclasses:"Warning: Not all classes ",
turnOnAccessibility:"Turn on accessibility features",
found:"Found",
probablyOnCampus:"probably on campus so you get no results.",
noResults:"No Results",
crnHelpText:"Copy these Catalog Numbers and go to <a href='https://wrem.sis.yorku.ca/Apps/WebObjects/REM.woa/wa/DirectAction/rem' target='_blank'><span>Registration and Enrolment Module</span></a> (REM) to enrol.",
gotoAddCoursePage:"Go to the Add Courses page",
turnOffAccessibility:"Turn off accessibility features",
close:"Close",
dec2:"December",
showSimilarOptions:"Show {} Similar Options",
sep:"Sep",
showCampusSelector:"Show campus selector",
classesFull:"All classes are full",
generateSchedulesTitle:"Click this to generate all the possible schedule results for the listed courses. This will send you to the Results Page",
creditsForFullTime:"or more credits for full-time.",
noClassesSatisfy:"No classes satisfy the corequisite requirements (See Class Remarks)",
verifyInternetConnection:"Verify your internet connection and try again",
inShoppingCart:"in Shopping Cart",
bothHonorsNHonors:"If you hide both honors and non-honors schedules then you will always have no results",
alreadyEnrolled:"(Already enrolled in this class)",
pleaseWait:" Please wait",
enterToSelect:"Press enter to select all classes",
to:"to",
currentlyOnAddCoursePage:"You are currently on the Add Courses Page",
campuses:"Campuses:",
noneVisible:"None Visible",
jul:"Jul",
sendToWorkSheetSubText:"",
overlapsPersonalTime:"All of these schedule results overlap personal time when you do not want to have classes.",
thu:"Thu",
jun:"Jun",
tipClickAndDragMobile:"<strong>Touch, hold for a second, and drag</strong> to indicate when you do not want to have classes. Schedules that avoid these times will be prioritized.",
collegeMustSelectFirst:"A college must be selected first.",
addTime:"Add Time",
added:"Added ",
fri2:"Friday",
available:"Available",
fullOrOnCampus:"probably full or on campus so you get no results.",
registrationOptional:"<br/>(Registration Optional)",
providedAtCampusesSelectedAbove:"provided at the campus(es) selected above. ",
hideSimilarOptions:"Hide Similar Options",
mon2:"Monday",
adding:"Adding ",
addOneMoreCourse:"You must add one or more courses before you can generate schedules.",
scheduleBlank:"The schedule is blank because<br/> you have no courses in your list.",
tue2:"Tuesday",
results:"results",
others:" others",
add:"Add",
firstScheduleResult:"The first schedule result does not.",
doActions:"Do Actions",
campus:"Campus: ",
mar2:"March",
allsectionsAreFull:"All sections are full",
list:"List",
numberBetweenAreSelectable:"<br/><br/>Numbers between parentheses () are selectable components such as Labs.",
noWaitlistable:" (no wait list classes available)",
aug:"Aug",
selectAll:"Select All",
getThisSchedule:"Get this Schedule",
unableToLoad:"Unable to load your enrollment state",
unscheduled:"(unscheduled)",
tipCheckOnlineClassesOnly:"One of your courses is set to 'Online classes only' and you are filtering out all schedules that contain online classes therefore you will always have no results. Check 'Online Classes', or go back and modify the Search criteria by changing the dropdown selection.",
selectAtleastOne:"Warning: You must select at least one honors class above<br/> for this to be an honors schedule.",
allThe:"All",
full:"Full",
drop:"Drop",
tipLearnOnDemandClassesOnly:"One of your courses is set to 'Learn on Demand classes only' and you are filtering out all schedules that contain online classes therefore you will always have no results. Check 'Online Classes', or go back and modify the Search criteria by changing the dropdown selection.",
enterToDeselect:"Press enter to deselect all classes",
thisCourseHasNoClasses:"This course has no classes ",
dropCourse:"Drop Course",
selectAdditionalCampuses:"Select additional campuses where you wish to take this course:",
showSimilarOption:"Show {} Similar Option",
jan2:"January",
alreadyInShopping:"(Already in Shopping Cart)",
totalCredits:"Total Credits",
test_example:"There is a {} in the {} by {}.",
nov:"Nov",
allOnCampusClassesOnly:"All courses have 'On Campus Classes Only' selected, therefore this checkbox does not apply",
personalCleared:"Personal times have been cleared.",
performAllActions:"Click to perform all the actions listed above",
currentlyOnResultsPage:"You are currently on the Results Page",
schedule:"Schedule",
seeClassRemarks:"See Class Remarks",
occurAtSelectedlocations:"occur only at the selected locations. Classes are at the following locations: ",
notFound:"not found",
allWithinColleges:"All %n within selected colleges",
fullOrOnline:"probably full or online so you get no results.",
select:"Select...",
noClasses:"No classes ",
oneOrMoreClassesFull:"One or more classes are full.",
none:"None",
selfConflicting:"All classes of this course are self-conflicting",
mon:"Mon",
tipClickAndDrag:"In the schedule grid, <strong>click and drag</strong> Personal Times to indicate when you do not want to have classes. You can also manually enter Personal Times in  Increase Accessibility mode.  Schedules that avoid these times will be prioritized.",
noCoursesToLoad:"No courses to load from PeopleSoft",
cleardTimesToAvoid:"Cleared all personal times.",
automaticallyAddDropSwap:"Automatically add/drop/swap your courses in your existing class schedule to be what is currently shown.",
fri:"Fri",
selectNone:"Select None",
feb2:"February",
oct:"Oct",
oct2:"October",
stayEnrolledIn:"Stay enrolled in",
period:"Term",
addressProblems:"You must address the problems mentioned before you can generate schedules.",
sectionFull:"Section is full",
youPinnedDown:"You pinned-down ",
learnOndemanClassesOnly:"Try Learn on Demand classes only",
examples:"Examples: Friday 2-9pm, MW 8-10, Fri 15-17",
overlapsNotWantClasses:"This schedule overlaps personal time when you do not want to have classes. ",
tipUseArrowsMobile:"<strong>Swipe left and right</strong> to quickly browse your generated schedule results.",
sat2:"Saturday",
deselectAllCampuses:"Deselect All Campuses",
classFull:"Class is full",
dontWant:"Click and drag to choose where you don't want classes",
theFirst:"The first",
sun2:"Sunday",
ofThe:"of the",
alreadyEnrolledFor:"You are already enrolled for this schedule",
cartDoesNotFilters:"The class in your cart does not occur within the selected filters.",
youMustIncludeCampus:"You must include the campus where this class is offered this term:",
clickToRemove:"Click on this block to remove it",
tipClickToPinMobile:"<strong>Tap on classes</strong> to pin them down temporarily. This will narrow the number of results.",
wed:"Wed",
addToCart:"Add to Cart",
campusMustBeSelectedFirst:"A campus must be selected first.",
may2:"May",
mar:"Mar",
ScheduleAlreadyInCart:"This schedule is already in your Shopping Cart",
clickToPin:"Click to pin down course",
scheduleResultsDoNot:"schedule results do not.",
may:"May",
ratingDecreases:"This rating decreases when classes that could be taken with the same cohort are the ones being selected.",
printSchedule:"Print Schedule",
waitListNotice:"",
clearTimesToAviodText:"Click and drag on the schedule above, or enter a time range here and click 'Add Time' to add it manually. Schedule results that avoid these times will be prioritized.",
ReviewExamples:"Could not understand input. Review examples.",
removed:"Removed course",
alreadyAdded:"You already added",
stillOpenForEnrollement:"still open for enrollment ",
selectAllCampuses:"Select All Campuses",
tipShareSaveMobile:"<strong>Share or save</strong> your search by copy-pasting your browser's unique URL.",
stayWaitlistedIn:"Stay wait listed in",
wasAdded:"was added",
feb:"Feb",
noClassesWithOpenSeats:"has no classes with open seats that do not conflict with this course",
noticeScheduleContains:"Notice: This schedule contains ",
generatedResults:"Generated Results",
allPeriods:"All Terms",
creditsYouNeed:"credits. You need",
returnToAddCourses:"Return to 'Add Courses'",
seats:"Seats",
youAreNotSigned:"You are not signed in",
weeksliderlabel:"Displaying Week of",
noCampusesSelectedAbove:"No campuses are selected above. ",
all:"All",
sep2:"September",
swap:"Swap",
tipOnCampusClassesOnly:"One of your courses is set to 'On-campus classes only' and you are filtering out all schedules that contain classes that are on campus therefore you will always have no results. Check 'On-campus classes', or go back and modify the Search criteria by changing the dropdown selection.",
chooseCampusToselectThisCourse:"To select this course, choose a campus where the course is still offered this term: ",
wed2:"Wednesday",
probablyOnline:"probably online so you get no results.",
instructor:"Instructor(s)",
timeblock:"timeblock",
keep:"Keep",
daylightSavingTimeMessage:"*FreedomProject observes Daylight Saving Time. Therefore:<br/><br/>Fall classes will begin 1 hour earlier than indicated here until DST ends the 1st Sunday of November. <br/><br/>Spring classes will begin an hour earlier than indicated here after the 2nd Sunday in March when DST begins.",
chooseTerm:"You must choose a session first.",
showSelector:"Toggle selector",
swapInCart:"Swap in Cart",
clearTimesToAviod:"Clear all Personal Times",
timezone:"Timezone: ",
hideSelector:"Hide selector",
hideCampusSelector:"Hide campus selector",
nov2:"November",
allNWithin:"All %n within selected campuses",
and:" and ",
changeSheduleFilter:"<br/><br/>Change your schedule filter or ",
of:"of",
tryOnlyClass:"Try all classes (1)",
crn:"Cat #",
jul2:"July",
noClassesSelected:"The course {} does not have any classes selected.",
sat:"Sat",
thu2:"Thursday",
colleges:"Colleges:",
decreaseAccessibility:"Disable Accessibility Features",
classesThatAre:" classes that are ",
onCampusClassesOnly:"Try On campus classes only",
aboveHaveSeatsAvailable:"above have seats available.<br/>",
courseConflict:"All classes of this course conflict with all classes of",
aug2:"August",
onlineClassesOnly:"Try Online classes only",
locations:"Locations:",
removethepins:"remove the pins",
};

// Example: i8n.s("test_example","cat","hat","seuss")
i8n.s = function(key,p0,p1,p2,p3,p4) {
	
	var str=key;
	if (this.hasOwnProperty(key)) {
		str=this[key];
	}
	
	if (!p0) return str;
	
	var p=0;
	p=str.indexOf("{}")+1;
	if (p<=0) {
		return str;
	}
	var pos = new Array();
	pos.push(p);
	do {
		p = str.indexOf("{}",p)+1;
		if (p>0) {
			pos.push(p);
		}
	} while (p>0);
	
	var s="";
	for (var i=0; i<pos.length; i++) {
		var i1=0;
		if (i>=1) i1=pos[i-1]+1;
		var i2=pos[i]-1;
		s+=str.substring(i1, i2);
		if (i==0 && p0) {
			s+=p0;	
		} else if (i==1 && p1) {
			s+=p1;
		} else if (i==2 && p2) {
			s+=p2;
		} else if (i==3 && p3) {
			s+=p3;
		} else if (i==4 && p4) {
			s+=p4;
		}
	}
	s+=str.substring(pos[pos.length-1]+1);
	return s;
}
